image: debian:bullseye

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_deploy

main:
  stage: test_deploy
  script:
    - apt update
    - apt install -y python3-pip
    - pip3 install poetry
    - poetry install
    - poetry run mkdocs build -d dist

.deploy_defaults: &deploy_defaults
  stage: test_deploy
  script:
    # Install system dependencies
    - apt update
    - apt install -y composer rsync python3-pip
    - pip3 install poetry
    - poetry install
    - poetry run mkdocs build -d dist
    # Add ssh key
    - mkdir -p ~/.ssh
    - echo "${DEPLOY_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa "${DEPLOY_HOST}" >> ~/.ssh/known_hosts
    # Install PHP dependencies
    - cd ./.gitlab-ci
    - "composer require --no-progress 'deployer/deployer: ^6.4' 'deployer/recipes: ^6.2'"
    # Deploy
    - ./vendor/bin/dep deploy "${CI_ENVIRONMENT_NAME}"
    - echo "Deployed to ${CI_ENVIRONMENT_URL}"

deploy_dev:
  only:
    refs:
      - main
  environment:
    name: development
    url: https://dbp-demo.tugraz.at/dev-guide
  artifacts:
    paths:
      - dist
  variables:
    DEPLOY_HOST: vpu01-demo.tugraz.at
    DEPLOY_KEY: "$DEPLOY_SSH_KEY"
  <<: *deploy_defaults
