site_name: Digital Blueprint Developer Guide
theme:
    name: material
    palette:
      primary: teal
      accent: teal
    logo: assets/logo.png
    favicon: assets/logo.png

extra_css:
  - assets/styles/styles.css
  - assets/styles/extra.css

extra_javascript:
  - assets/js/mermaid.min.js
  - assets/js/main.js

repo_url: https://gitlab.tugraz.at/dbp/dev-guide
edit_uri: edit/main/docs/

markdown_extensions:
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
  - index.md
  - contribute.md
  - Web Component Framework:
    - frontend/index.md
    - frontend/getting_started.md
    - frontend/components.md
    - frontend/activities.md
    - frontend/configuration.md
    - frontend/theming.md
    - frontend/keycloak_integration.md
    - Developer Guide:
      - frontend/dev/coding_standard.md
      - frontend/dev/accessibility.md
      - frontend/dev/web_components_guidelines.md
      - frontend/dev/testing.md
      - frontend/dev/build_tooling.md
      - frontend/dev/browser_support.md
      - frontend/dev/remote_firefox_debugging.md
      - frontend/dev/assets.md
      - frontend/dev/topics.md

  - Relay API Gateway:
    - relay/index.md
    - relay/getting_started.md
    - relay/extending_with_bundles.md
    - relay/config.md
    - relay/bundle_config.md
    - relay/debugging.md
    - relay/production.md
    - relay/update.md
    - relay/reverse_proxies.md
    - relay/faq.md
    - Available Bundles:
      - Core Bundle:
        - relay/bundles/core/index.md
        - relay/bundles/core/config.md
        - relay/bundles/core/cron.md
        - relay/bundles/core/queue.md
        - relay/bundles/core/locks.md
        - relay/bundles/core/errors.md
      - Auth Bundle:
        - relay/bundles/auth/index.md
        - relay/bundles/auth/config.md
        - relay/bundles/auth/roles.md
      - Base Person Bundle:
        - relay/bundles/base-person/index.md
      - Base Organization Bundle:
        - relay/bundles/base-organization/index.md
      - Checking Bundle:
        - relay/bundles/checkin/index.md
      - Electronic Signature Bundle:
        - relay/bundles/esign/index.md
        - relay/bundles/esign/config.md
        - relay/bundles/esign/advanced_flow.md
        - relay/bundles/esign/advanced_pdf_signing.md
        - relay/bundles/esign/qualified_flow.md
        - relay/bundles/esign/positioning.md
      - ALMA Bundle:
        - relay/bundles/alma/index.md
      - Nextcloud Bundle:
        - relay/bundles/nextcloud/index.md
      - Authentic Document Bundle:
        - relay/bundles/authentic-document/index.md
      - Knowledgebase Bundle:
        - relay/bundles/knowledgebase/index.md
      - Location Check In Bundle:
        - relay/bundles/location-check-in/index.md
      - Greenlight Bundle:
        - relay/bundles/greenlight/index.md
        - relay/bundles/greenlight/config.md
        - CAMPUSonline Connector:
          - relay/bundles/greenlight-connector-campusonline/index.md
          - relay/bundles/greenlight-connector-campusonline/config.md
    - Developer Guide:
      - relay/dev/new_bundle.md
      - relay/dev/bundle_config.md
      - relay/dev/ide_integration.md
      - relay/dev/access_control.md
      - relay/dev/naming.md
      - relay/dev/bundle_architecture.md
      - relay/dev/coding_standard.md
      - relay/dev/guidelines.md
      - relay/dev/faq.md
      - Keycloak Integration:
        - relay/keycloak/index.md
        - relay/keycloak/keycloak_scopes.md
        - relay/keycloak/keycloak_audience.md
        - relay/keycloak/scopes.md
        - relay/keycloak/client_credentials.md
  - licenses.md
  - opensource.md
  - logo/logo.md
  - How-Tos:
    - howtos/about.md
    - howtos/deployment.md
    - howtos/docker.md
    - howtos/forks.md
  - demo_access.md
  - contact.md