site_name: Digital Blueprint Developer Guide
theme:
    name: material
    palette:
      primary: teal
      accent: teal
    logo: assets/logo.png
    favicon: assets/logo.png

extra_css:
  - assets/styles/styles.css
  - assets/styles/extra.css

extra_javascript:
  - assets/js/mermaid.min.js
  - assets/js/main.js

repo_url: https://gitlab.tugraz.at/dbp/dev-guide
edit_uri: edit/main/docs/

markdown_extensions:
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
  - index.md
  - contribute.md
  - Web Component Framework:
    - frontend/index.md
    - frontend/getting_started.md
    - frontend/components.md
    - frontend/activities.md
    - frontend/topics.md
    - frontend/configuration.md
    - frontend/theming.md
    - frontend/assets.md
    - frontend/remote_firefox_debugging.md
    - frontend/testing.md
    - frontend/browser_support.md
    - frontend/build_tooling.md
    - frontend/frontend_auth.md
  - Relay API Gateway:
    - relay/index.md
    - relay/getting_started.md
    - relay/new_bundle.md
    - relay/bundle_config.md
    - relay/config.md
    - relay/production.md
    - API Bundles:
      - Core Bundle:
        - relay/bundles/core/index.md
        - relay/bundles/core/config.md
        - relay/bundles/core/cron.md
        - relay/bundles/core/queue.md
        - relay/bundles/core/locks.md
        - relay/bundles/core/errors.md
      - Auth Bundle:
        - relay/bundles/auth/index.md
        - relay/bundles/auth/config.md
        - relay/bundles/auth/roles.md
      - Base Person Bundle:
        - relay/bundles/base-person/index.md
      - Base Organization Bundle:
        - relay/bundles/base-organization/index.md
      - Checking Bundle:
        - relay/bundles/checkin/index.md
      - Electronic Signature Bundle:
        - relay/bundles/esign/index.md
        - relay/bundles/esign/config.md
        - relay/bundles/esign/advanced_flow.md
        - relay/bundles/esign/advanced_pdf_signing.md
        - relay/bundles/esign/qualified_flow.md
      - ALMA Bundle:
        - relay/bundles/alma/index.md
      - Nextcloud Bundle:
        - relay/bundles/nextcloud/index.md
      - Authentic Document Bundle:
        - relay/bundles/authentic-document/index.md
      - Knowledgebase Bundle:
        - relay/bundles/knowledgebase/index.md
      - Location Check In Bundle:
        - relay/bundles/location-check-in/index.md
    - relay/ide_integration.md
    - relay/access_control.md
    - relay/naming.md
    - Keycloak Integration:
      - relay/keycloak/index.md
      - relay/keycloak/keycloak_scopes.md
      - relay/keycloak/keycloak_audience.md
      - relay/keycloak/scopes.md
      - relay/keycloak/non_user_access.md
    - relay/faq.md
  - licenses.md
  - opensource.md
  - logo/logo.md
  - How-Tos:
    - howtos/about.md
    - howtos/deployment.md
    - howtos/docker.md
    - howtos/forks.md
  - demo_access.md
  - contact.md