site_name: digital blueprint handbook
theme:
    font: false
    name: material
    palette:
      - scheme: default
        primary: white
        accent: indigo
    logo: assets/dbp_logo_small_on_white.svg
    favicon: assets/apple-touch-icon.png
    custom_dir: overrides

extra_css:
  - assets/styles/styles.css
  - assets/styles/extra.css
  - assets/styles/fonts.css

extra_javascript:
  - assets/js/mermaid.min.js
  - assets/js/main.js

repo_url: https://gitlab.tugraz.at/dbp/handbook
edit_uri: edit/main/docs/

markdown_extensions:
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.highlight:
        extend_pygments_lang:
          - name: php
            lang: php
            options:
              startinline: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
  - index.md

  - Relay API Gateway:
    - relay/index.md

  - Frontend Framework:
    - frontend/index.md

  - Corporate Design:
    - cd/index.md
