site_name: digital blueprint handbook
theme:
    font: false
    name: material
    palette:
      - scheme: default
        primary: white
        accent: indigo
    logo: cd/assets/logo/dbp_logo_small_on_white.svg
    favicon: cd/assets/apple-touch-icon.png
    custom_dir: overrides
    features:
      - content.action.edit
      - content.code.copy

plugins:
  - search:
  # https://github.com/mkdocs/mkdocs-redirects
  - redirects:
      redirect_maps:

extra_css:
  - assets/styles/styles.css
  - assets/styles/extra.css
  - assets/styles/fonts.css

extra_javascript:
  - assets/js/mermaid.min.js
  - assets/js/main.js

repo_url: https://github.com/digital-blueprint/handbook
edit_uri: edit/main/docs/

markdown_extensions:
    - md_in_html
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.highlight:
        extend_pygments_lang:
          - name: php
            lang: php
            options:
              startinline: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
  - index.md

  - Blueprints:
    - blueprints/index.md
    - blueprints/greenlight.md
    - blueprints/check-in.md
    - blueprints/esign.md
    - blueprints/plan.md

  - Components:

    - Apps:
      - components/app/mono.md

    - API:
      - components/api/server-template.md
      - components/api/core-bundle.md
      - components/api/auth-bundle.md
      - components/api/base-person-connector-ldap-bundle.md
      - components/api/greenlight-connector-campusonline-bundle.md
      - Core Bundle:
        - components/api/core/index.md
      - Auth Bundle:
        - components/api/auth/index.md
        - components/api/auth/config.md
        - components/api/auth/roles.md
      - Base Person Bundle:
        - components/api/base-person/README.md
        - LDAP Connector:
          - components/api/base-person-connector-ldap/README.md
          - components/api/base-person-connector-ldap/config.md
      - Base Organization Bundle:
        - components/api/base-organization/index.md
      - Electronic Signature Bundle:
        - components/api/esign/index.md
        - components/api/esign/config.md
        - components/api/esign/advanced_flow.md
        - components/api/esign/advanced_pdf_signing.md
        - components/api/esign/qualified_flow.md
        - components/api/esign/positioning.md
        - components/api/esign/cli_commands.md
      - Sublibrary Bundle:
        - components/api/sublibrary/index.md
      - Authentic Documents Bundle:
        - components/api/authentic-documents/README.md
      - Check In Bundle:
        - components/api/check-in/index.md
      - Greenlight Bundle:
        - components/api/greenlight/index.md
        - components/api/greenlight/config.md
        - CAMPUSonline Connector:
          - components/api/greenlight-connector-campusonline/index.md
          - components/api/greenlight-connector-campusonline/config.md
      - Mono Bundle:
        - components/api/mono/index.md
        - components/api/mono/config.md
        - components/api/mono/logging.md
        - CAMPUSonline Connector:
          - components/api/mono-connector-campusonline/index.md
          - components/api/mono-connector-campusonline/config.md
        - PayUnity Connector:
          - components/api/mono-connector-payunity/index.md
          - components/api/mono-connector-payunity/config.md
        - Generic Connector:
          - components/api/mono-connector-generic/index.md
      - Dispatch Bundle:
        - components/api/dispatch/README.md
        - components/api/dispatch/config.md
        - components/api/dispatch/authz.md
        - components/api/dispatch/database.md
        - components/api/dispatch/cli.md
        - components/api/dispatch/api.md

    - Supporting Software:
      - components/supporting-software/pdf-as.md

  - Frameworks:

    - frameworks/index.md

    - Relay API Gateway:
      - frameworks/relay/index.md

      - User Guide:
        - frameworks/relay/user/index.md
        - frameworks/relay/user/error_handling.md
        - frameworks/relay/user/pagination.md
        - frameworks/relay/user/translations.md
        - frameworks/relay/user/client_credentials.md

      - Administration Guide:
        - frameworks/relay/admin/index.md
        - frameworks/relay/admin/extending_with_bundles.md
        - frameworks/relay/admin/production.md
        - frameworks/relay/admin/config.md
        - frameworks/relay/admin/access_control.md
        - frameworks/relay/admin/expression_language.md
        - frameworks/relay/admin/locks.md
        - frameworks/relay/admin/queue.md
        - frameworks/relay/admin/cron.md
        - frameworks/relay/admin/database.md
        - frameworks/relay/admin/reverse_proxies.md
        - frameworks/relay/admin/debugging.md
        - frameworks/relay/admin/update.md
        - frameworks/relay/admin/faq.md

      - Developer Guide:
        - frameworks/relay/dev/index.md
        - frameworks/relay/dev/getting_started.md
        - frameworks/relay/dev/new_bundle.md
        - frameworks/relay/dev/bundle_config.md
        - frameworks/relay/dev/access_control.md
        - frameworks/relay/dev/cron.md
        - frameworks/relay/dev/errors.md
        - frameworks/relay/dev/queue.md
        - frameworks/relay/dev/logging.md
        - frameworks/relay/dev/local_data.md
        - frameworks/relay/dev/locks.md
        - frameworks/relay/dev/api.md
        - frameworks/relay/dev/cors_headers.md
        - frameworks/relay/dev/cli_commands.md
        - frameworks/relay/dev/health_checks.md
        - frameworks/relay/dev/naming.md
        - frameworks/relay/dev/guidelines.md
        - frameworks/relay/dev/faq.md
        - frameworks/relay/dev/coding_standard.md
        - frameworks/relay/dev/ide_integration.md
        - frameworks/relay/dev/datetime.md
        - frameworks/relay/dev/pagination.md
        - frameworks/relay/dev/translations.md
        - frameworks/relay/dev/base_entities.md
        - frameworks/relay/dev/hooks.md
        - frameworks/relay/dev/database.md
        - frameworks/relay/dev/sysreq_policy.md

      - HowTos:
        - frameworks/relay/howtos/keycloak_scopes.md
        - frameworks/relay/howtos/keycloak_audience.md
        - frameworks/relay/howtos/service_account.md

    - Frontend Framework:

      - frameworks/frontend/index.md
      - frameworks/frontend/getting_started.md
      - frameworks/frontend/components.md
      - frameworks/frontend/activities.md
      - frameworks/frontend/configuration.md
      - frameworks/frontend/theming.md
      - frameworks/frontend/keycloak_integration.md

      - Developer Guide:
        - frameworks/frontend/dev/coding_standard.md
        - frameworks/frontend/dev/accessibility.md
        - frameworks/frontend/dev/ui_guideline.md
        - frameworks/frontend/dev/web_components_guidelines.md
        - frameworks/frontend/dev/testing.md
        - frameworks/frontend/dev/build_tooling.md
        - frameworks/frontend/dev/browser_support.md
        - frameworks/frontend/dev/remote_firefox_debugging.md
        - frameworks/frontend/dev/assets.md
        - frameworks/frontend/dev/topics.md
        - frameworks/frontend/dev/faq.md
        - frameworks/frontend/dev/translations.md

  - Corporate Design:
    - cd/logo.md
    - cd/naming.md
    - cd/colors.md
    - cd/fonts.md
    - cd/secondary-design-elements.md
    - cd/icons.md
    - cd/apps.md
  - How-Tos:
    - howtos/docker.md

  - demo_access.md
  - contribute.md
  - contact.md