name: main

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python (pip)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: .github/workflows/main.yml

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade poetry==1.4.2

      - name: Setup Python (poetry)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Build
        run: |
          poetry run mkdocs build

      - name: Pack result
        run: |
          tar -czf site.tar.gz ./site

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: site.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: ${{ github.ref_name }}

    steps:
      - name: Deploy and wait for completion
        if: github.ref == 'refs/heads/main'
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: 'gitlab.tugraz.at'
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: '21238'
          ref: 'main'
          variables: '{"UPSTREAM_PROJECT_PATH":"dbp/handbook","UPSTREAM_COMMIT_BRANCH":"${{ github.ref_name }}","UPSTREAM_COMMIT_SHA":"${{ github.ref_name }}"}'

  deploy-docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: (github.repository == 'digital-blueprint/handbook' && github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in
        run: |
          echo "$TOKEN" | docker login ghcr.io --username "$USERNAME" --password-stdin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/digital-blueprint/handbook:latest .
      - name: Deploy image
        run: |
          docker push ghcr.io/digital-blueprint/handbook:latest
